// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvLiSD7LT8oE1Qlwd8ObNK2zFlzre4cjM',
    appId: '1:65158076811:web:0dc69671614760ec0d778e',
    messagingSenderId: '65158076811',
    projectId: 'lendr-26e5c',
    authDomain: 'lendr-26e5c.firebaseapp.com',
    storageBucket: 'lendr-26e5c.appspot.com',
    measurementId: 'G-LDG55Z6NB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3dLIV_2IqDZwXSzyyyGu2ThyJTRkCUU4',
    appId: '1:65158076811:android:a2f907f0e2df0dca0d778e',
    messagingSenderId: '65158076811',
    projectId: 'lendr-26e5c',
    storageBucket: 'lendr-26e5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGA3T7HogYCabHvYxnq6A4VCr2vihjtJM',
    appId: '1:65158076811:ios:2f8a8f37ffbf545b0d778e',
    messagingSenderId: '65158076811',
    projectId: 'lendr-26e5c',
    storageBucket: 'lendr-26e5c.appspot.com',
    iosBundleId: 'com.example.lendr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGA3T7HogYCabHvYxnq6A4VCr2vihjtJM',
    appId: '1:65158076811:ios:2f8a8f37ffbf545b0d778e',
    messagingSenderId: '65158076811',
    projectId: 'lendr-26e5c',
    storageBucket: 'lendr-26e5c.appspot.com',
    iosBundleId: 'com.example.lendr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvLiSD7LT8oE1Qlwd8ObNK2zFlzre4cjM',
    appId: '1:65158076811:web:230fd516bebb53e50d778e',
    messagingSenderId: '65158076811',
    projectId: 'lendr-26e5c',
    authDomain: 'lendr-26e5c.firebaseapp.com',
    storageBucket: 'lendr-26e5c.appspot.com',
    measurementId: 'G-Y41FKVMH3Y',
  );
}
